workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_NAME: "YourApp"
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Set iOS deployment target to 13.0
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/' ios/Podfile || echo "platform :ios, '13.0'" >> ios/Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      ios:
        use_automatic_signing: true
        app_store_connect:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: Encrypted(app_store_connect_private_key.p8)
          team_id: $APP_STORE_CONNECT_TEAM_ID
          bundle_id: $BUNDLE_ID
